<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>75c6775f-04d5-4e9d-925e-2c590efa3e84</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\shared-libs\MigrationsExtensions\MigrationsExtensions.csproj" />
    <ProjectReference Include="..\Workspaces.Application\Workspaces.Application.csproj" />
    <ProjectReference Include="..\Workspaces.Infrastructure\Workspaces.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared-libs\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
