<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cd64f3d9-d814-4d3a-9cb6-a671111d79bd</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Users.Application\Users.Application.csproj" />
    <ProjectReference Include="..\Users.Infrastructure\Users.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared-libs\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\shared-libs\MigrationsExtensions\MigrationsExtensions.csproj" />
  </ItemGroup>
</Project>
