<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Users.Application\Users.Application.csproj" />
    <ProjectReference Include="..\Users.Infrastructure\Users.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\shared-libs\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
