<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="*" />
    <PackageReference Include="MediatR" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tasks.Domain\Tasks.Domain.csproj" />
    <ProjectReference Include="..\..\..\shared-libs\DomainFramework\DomainFramework.csproj" />
    <ProjectReference Include="..\..\..\shared-libs\Messaging\Messaging.csproj" />
  </ItemGroup>
</Project>
